package:
  name: dxfile
  version: '0.4'

source:
  git_url: https://github.com/data-exchange/dxfile.git
  
build:
  number: 0

requirements:
  build:
    - python
    - setuptools
 
  run:
    - python
    - h5py

test:
  # Python imports
  imports:
    - dxfile
    - dxfile.dxtomo

about:
  home: http://dxfile.readthedocs.org
  license: BSD-3
  summary: 'Reader/Writer for Data Exchange files.'
