package:
  name: dxfile
  version: '0.3.2'

source:
  path: dxfile
  
build:
  number: 0

requirements:
  build:
    - python
    - setuptools
 
  run:
    - python
    - h5py

test:
  # Python imports
  imports:
    - dxfile
    - dxfile.dxtomo

about:
  home: http://dxfile.readthedocs.org
  license: BSD
  summary: 'Definition and Writer for Data Exchange files.'

